sudo: false
language: python
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
- PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_e2c84e1c574e_key -iv $encrypted_e2c84e1c574e_iv
  -in credentials.json.enc -out credentials.json -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- gcloud auth activate-service-account --key-file credentials.json
install:
- pip install ansible
- wget https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip
- unzip packer_1.1.3_linux_amd64.zip
script:
- packer build -var 'proj_id=docker-181710' -var 's_im_fam=ubuntu-1604-lts' ubuntu16.json
