sudo: false
language: python
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
- PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1 GOOGLE_APPLICATION_CREDENTIALS="credentials.json"
  PROJECT="docker-181710"
before_install:
- openssl aes-256-cbc -K $encrypted_e2c84e1c574e_key -iv $encrypted_e2c84e1c574e_iv
  -in secrets.zip.enc -out secrets.zip -d
- unzip secrets.zip
- if [ ! -d ${HOME}/google-cloud-sdk/bin ]; then curl https://sdk.cloud.google.com | bash;
  fi
- gcloud auth activate-service-account --key-file credentials.json
install:
- pip install ansible
- wget https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip
- unzip packer_1.1.3_linux_amd64.zip
script:
- packer build -var "proj_id=$PROJECT" -var "s_im_fam=ubuntu-1604-lts" ubuntu16.json
- export IMAGE=`jq -r '.builds[0].artifact_id' output.json`
- echo $IMAGE
- gcloud compute instances create "travis-reddit-app" --image "$IMAGE" --zone "europe-west1-b"
  --project $PROJECT
- export EXTERNAL_IP=`gcloud compute instances list --project $PROJECT --filter="name=travis-reddit-app"
  --format='value(EXTERNAL_IP)'`
- echo $EXTERNAL_IP
- ansible-playbook -i "$EXTERNAL_IP," packer_deploy.yml
- sleep 5 && curl -s -o /dev/null -I -w "%{http_code}" --retry 10 --retry-delay 10
  $EXTERNAL_IP:9292
after_script:
- gcloud compute images delete --project $PROJECT -q $IMAGE
- gcloud compute instances delete -q travis-reddit-app --zone "europe-west1-b" --project
  $PROJECT
